### ISSUE TITLE
Melhoria de logica

### ISSUE THREAD

**Issue by thiagovictorino** [leonardopenz10/bodyinform#12]
Aqui nesse arquivo https://github.com/leonardopenz10/bodyinform/blob/master/models/login.js

Pode ser simplificado por

```js
function verifyFields(user, password) {
  return typeof user === "string" && typeof password === "string");
}
```
Sempre que vc tem uma funcao que retorna um boleano, veja se nao da para simplificar assim

**Comment by leonardopenz** [comment]
Oi @thiagovictorino 

Obrigado pela dica, realmente fica mais simples e fácil de entender dessa forma.
